# Generated by Django 3.0.8 on 2020-07-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Custom', 'Custom')], default='Custom', max_length=30),
        ),
    ]
