# Generated by Django 3.0.8 on 2020-07-21 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.FileField(default='profiles/default/default.png', upload_to='profiles')),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('connection', models.CharField(blank=True, max_length=50)),
                ('follower', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
